services:
  nginx:
    image: nginx:1.25.4-alpine
    volumes:
      - .:/var/www
      - ./docker/nginx/templates:/etc/nginx/templates
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    depends_on:
      - php-fpm
    restart: on-failure

  php-fpm:
    build:
      context: ./docker/php
    volumes:
      - .:/var/www
    restart: on-failure

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: Blog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql 
    ports:
      - "5432:5432"
    restart: on-failure

volumes:
  postgres_data:
